
CREATE TABLE TFT_FILE_INFO
(
	FILE_ID  CHAR(36) NOT NULL,
	ORIGINAL_FILE  VARCHAR(256) NOT NULL,
	FILEMD5  CHAR(32) NOT NULL,
	ACTUAL_FILE_NAME  VARCHAR(50) NOT NULL,
	 PRIMARY KEY (FILE_ID)
)
;



CREATE UNIQUE INDEX ift_file_info ON TFT_FILE_INFO
(
	FILE_ID
)
;



CREATE TABLE TFT_FILE_REGISTRY
(
	FILE_PATH  VARCHAR(100) NOT NULL,
	FILEMD5  CHAR(32) NOT NULL,
	RER_COUNT  INTEGER NULL,
	FILE_SIZE  VARCHAR(20) NOT NULL,
	 PRIMARY KEY (FILEMD5)
)
;



CREATE UNIQUE INDEX ift_file_registry ON TFT_FILE_REGISTRY
(
	FILEMD5
)
;



alter TABLE TFT_FILE_INFO COMMENT = '文件信息表' ENGINE=InnoDB DEFAULT CHARSET=utf8;
 
    ALTER TABLE TFT_FILE_INFO CHANGE COLUMN FILE_ID FILE_ID CHAR(36) NOT NULL COMMENT '文件ID';
           
      ALTER TABLE TFT_FILE_INFO CHANGE COLUMN ORIGINAL_FILE ORIGINAL_FILE VARCHAR(256) NOT NULL COMMENT '原文件名';
           
      ALTER TABLE TFT_FILE_INFO CHANGE COLUMN FILEMD5 FILEMD5 CHAR(32) NOT NULL COMMENT '文件MD5';
           
      ALTER TABLE TFT_FILE_INFO CHANGE COLUMN ACTUAL_FILE_NAME ACTUAL_FILE_NAME VARCHAR(50) NOT NULL COMMENT '实际文件名';
           
      
alter TABLE TFT_FILE_REGISTRY COMMENT = '文件注册表' ENGINE=InnoDB DEFAULT CHARSET=utf8;
 
    ALTER TABLE TFT_FILE_REGISTRY CHANGE COLUMN FILE_PATH FILE_PATH VARCHAR(100) NOT NULL COMMENT '文件路径';
           
      ALTER TABLE TFT_FILE_REGISTRY CHANGE COLUMN FILEMD5 FILEMD5 CHAR(32) NOT NULL COMMENT '文件MD5';
           
      ALTER TABLE TFT_FILE_REGISTRY CHANGE COLUMN RER_COUNT RER_COUNT INTEGER  COMMENT '引用次数';
           
      ALTER TABLE TFT_FILE_REGISTRY CHANGE COLUMN FILE_SIZE FILE_SIZE VARCHAR(20) NOT NULL COMMENT '文件大小';