
CREATE TABLE TST_SCHEDULE
(
	SCHEDULE_ID  CHAR(36) NOT NULL,
	EXECUTE_PATH  VARCHAR(20) NOT NULL,
	TIME_EXPRESSION  VARCHAR(20) NOT NULL,
	EXECUTE_MODULE  VARCHAR(20) NOT NULL,
	EXECUTE_PARAM  VARCHAR(2000) NULL,
	 PRIMARY KEY (SCHEDULE_ID)
)
;



CREATE TABLE TST_SCHEDULE_ITEM
(
	SCHEDULE_ID  CHAR(36) NOT NULL,
	MESSAGE  VARCHAR(4000) NOT NULL,
	TASK_ID  CHAR(36) NOT NULL,
	START_TIME  DATETIME NOT NULL,
	END_TIME  DATETIME NOT NULL,
	 PRIMARY KEY (TASK_ID)
)
;



alter TABLE TST_SCHEDULE COMMENT = '定时任务表' ENGINE=InnoDB DEFAULT CHARSET=utf8;
 
    ALTER TABLE TST_SCHEDULE CHANGE COLUMN SCHEDULE_ID SCHEDULE_ID CHAR(36) NOT NULL COMMENT '定时任务ID';
           
      ALTER TABLE TST_SCHEDULE CHANGE COLUMN EXECUTE_PATH EXECUTE_PATH VARCHAR(20) NOT NULL COMMENT '执行路径';
           
      ALTER TABLE TST_SCHEDULE CHANGE COLUMN TIME_EXPRESSION TIME_EXPRESSION VARCHAR(20) NOT NULL COMMENT '时间表达式';
           
      ALTER TABLE TST_SCHEDULE CHANGE COLUMN EXECUTE_MODULE EXECUTE_MODULE VARCHAR(20) NOT NULL COMMENT '执行模块';
           
      ALTER TABLE TST_SCHEDULE CHANGE COLUMN EXECUTE_PARAM EXECUTE_PARAM VARCHAR(2000)  COMMENT '执行参数';
           
      
alter TABLE TST_SCHEDULE_ITEM COMMENT = '定时任务条目表' ENGINE=InnoDB DEFAULT CHARSET=utf8;
 
    ALTER TABLE TST_SCHEDULE_ITEM CHANGE COLUMN SCHEDULE_ID SCHEDULE_ID CHAR(36) NOT NULL COMMENT '定时任务ID';
           
      ALTER TABLE TST_SCHEDULE_ITEM CHANGE COLUMN MESSAGE MESSAGE VARCHAR(4000) NOT NULL COMMENT '消息';
           
      ALTER TABLE TST_SCHEDULE_ITEM CHANGE COLUMN TASK_ID TASK_ID CHAR(36) NOT NULL COMMENT '任务ID';
           
      ALTER TABLE TST_SCHEDULE_ITEM CHANGE COLUMN START_TIME START_TIME DATETIME NOT NULL COMMENT '开始时间';
           
      ALTER TABLE TST_SCHEDULE_ITEM CHANGE COLUMN END_TIME END_TIME DATETIME NOT NULL COMMENT '结束时间';
           