
CREATE TABLE TPT_CONTROL
(
	APPLICATION_ID  CHAR(36) NOT NULL,
	DESCR  VARCHAR(150) NULL,
	ROLE_ID  CHAR(36) NOT NULL,
	PERMISSION_ID  CHAR(36) NOT NULL,
	MENU_ID  CHAR(36) NOT NULL,
	NAVIGATION_ID  CHAR(36) NOT NULL,
	 PRIMARY KEY (APPLICATION_ID)
)
;



CREATE TABLE TPT_DOMAIN_MANAGER
(
	DOMAIN_MANAGE_ID  VARCHAR(20) NULL,
	PARENT_DOMAIN_ID  VARCHAR(20) NULL,
	DOMAIN_CODE  VARCHAR(20) NULL,
	DOMAIN_NAME  VARCHAR(20) NULL,
	REMARKS  VARCHAR(20) NULL,
	ROLE_ID  CHAR(36) NOT NULL,
	PERMISSION_ID  CHAR(36) NOT NULL,
	 PRIMARY KEY (DOMAIN_MANAGE_ID)
)
;



CREATE TABLE TPT_MENU
(
	MENU_ID  CHAR(36) NOT NULL,
	PARENT_MENU_ID  CHAR(36) NULL,
	MENU_NAME  VARCHAR(10) NULL,
	TERMINAL_CATEGORY  CHAR(10) NULL,
	DOMAIN_MANAGE_ID  VARCHAR(20) NOT NULL,
	ROUTING_ID  CHAR(36) NOT NULL,
	 PRIMARY KEY (MENU_ID)
)
;



CREATE TABLE TPT_NAVIGATION
(
	NAVIGATION_ID  CHAR(36) NOT NULL,
	PARENT_ID  CHAR(36) NULL,
	NAVIGATION_NAME  VARCHAR(10) NULL,
	PATH  VARCHAR(20) NULL,
	DESCR  VARCHAR(50) NULL,
	MENU_ID  CHAR(36) NOT NULL,
	ROUTING_ID  CHAR(36) NOT NULL,
	 PRIMARY KEY (NAVIGATION_ID)
)
;



CREATE TABLE TPT_PERMISSION
(
	PERMISSION_ID  CHAR(36) NOT NULL,
	PERMISSION_NAME  CHAR(10) NOT NULL,
	DESCR  VARCHAR(100) NULL,
	 PRIMARY KEY (PERMISSION_ID)
)
;



CREATE TABLE TPT_PERMISSION_MATRIX
(
	ROLE_ID  CHAR(36) NOT NULL,
	PERMISSION_ID  CHAR(36) NOT NULL,
	 PRIMARY KEY (ROLE_ID,PERMISSION_ID)
)
;



CREATE TABLE TPT_RESOURCE
(
	RESOURCES_GROUP_ID  CHAR(36) NOT NULL,
	PARENT_RESOURCES_GROUP_ID  CHAR(36) NULL,
	GROUP_NAME  VARCHAR(20) NOT NULL,
	DESCR  VARCHAR(50) NULL,
	ROLE_ID  CHAR(36) NOT NULL,
	PERMISSION_ID  CHAR(36) NOT NULL,
	LEVEL  INTEGER NULL,
	 PRIMARY KEY (RESOURCES_GROUP_ID)
)
;



CREATE TABLE TPT_ROLE
(
	ROLE_ID  CHAR(36) NOT NULL,
	ROLE_NAME  CHAR(10) NOT NULL,
	DESCR  VARCHAR(50) NULL,
	 PRIMARY KEY (ROLE_ID)
)
;



CREATE TABLE TPT_ROUTER
(
	ROUTING_ID  CHAR(36) NOT NULL,
	URL  VARCHAR(256) NULL,
	PARAM  VARCHAR(2000) NULL,
	REMARKS  VARCHAR(20) NULL,
	DOMAIN_MANAGE_ID  VARCHAR(20) NOT NULL,
	ROLE_ID  CHAR(36) NOT NULL,
	PERMISSION_ID  CHAR(36) NOT NULL,
	 PRIMARY KEY (ROUTING_ID)
)
;



CREATE TABLE TPT_STYLE
(
	SYTLE_ID  VARCHAR(20) NULL,
	SYTLE_NAME  VARCHAR(20) NULL,
	SYTLE_DESCR  VARCHAR(20) NULL,
	USER_ID  CHAR(36) NULL,
	 PRIMARY KEY (SYTLE_ID)
)
;



CREATE TABLE TPT_USER
(
	USER_ID  CHAR(36) NOT NULL,
	USER_CATEGORY  CHAR(10) NULL,
	ROLE_ID  CHAR(36) NOT NULL,
	PERMISSION_ID  CHAR(36) NOT NULL,
	RESOURCES_GROUP_ID  CHAR(36) NOT NULL,
	 PRIMARY KEY (USER_ID)
)
;



CREATE TABLE TPT_WEIXIN
(
	WEIXIN_NO  VARCHAR(18) NOT NULL,
	RESOURCES_GROUP_ID  CHAR(36) NOT NULL,
	WEIXIN_USER_ID  CHAR(36) NOT NULL,
	CREATE_TIME  VARCHAR(20) NOT NULL,
	 PRIMARY KEY (WEIXIN_USER_ID)
)
;



alter TABLE TPT_CONTROL COMMENT = '访问控制表' ENGINE=InnoDB DEFAULT CHARSET=utf8;
 
    ALTER TABLE TPT_CONTROL CHANGE COLUMN APPLICATION_ID APPLICATION_ID CHAR(36) NOT NULL COMMENT '应用ID';
           
      ALTER TABLE TPT_CONTROL CHANGE COLUMN DESCR DESCR VARCHAR(150)  COMMENT '描述';
           
      ALTER TABLE TPT_CONTROL CHANGE COLUMN ROLE_ID ROLE_ID CHAR(36) NOT NULL COMMENT '角色ID';
           
      ALTER TABLE TPT_CONTROL CHANGE COLUMN PERMISSION_ID PERMISSION_ID CHAR(36) NOT NULL COMMENT '权限ID';
           
      ALTER TABLE TPT_CONTROL CHANGE COLUMN MENU_ID MENU_ID CHAR(36) NOT NULL COMMENT '菜单ID';
           
      ALTER TABLE TPT_CONTROL CHANGE COLUMN NAVIGATION_ID NAVIGATION_ID CHAR(36) NOT NULL COMMENT '导航ID';
           
      
alter TABLE TPT_DOMAIN_MANAGER COMMENT = '域管理表' ENGINE=InnoDB DEFAULT CHARSET=utf8;
 
    ALTER TABLE TPT_DOMAIN_MANAGER CHANGE COLUMN DOMAIN_MANAGE_ID DOMAIN_MANAGE_ID VARCHAR(20)  COMMENT '域管理ID';
           
      ALTER TABLE TPT_DOMAIN_MANAGER CHANGE COLUMN PARENT_DOMAIN_ID PARENT_DOMAIN_ID VARCHAR(20)  COMMENT '父域ID';
           
      ALTER TABLE TPT_DOMAIN_MANAGER CHANGE COLUMN DOMAIN_CODE DOMAIN_CODE VARCHAR(20)  COMMENT '域编码';
           
      ALTER TABLE TPT_DOMAIN_MANAGER CHANGE COLUMN DOMAIN_NAME DOMAIN_NAME VARCHAR(20)  COMMENT '域名称';
           
      ALTER TABLE TPT_DOMAIN_MANAGER CHANGE COLUMN REMARKS REMARKS VARCHAR(20)  COMMENT '备注';
           
      ALTER TABLE TPT_DOMAIN_MANAGER CHANGE COLUMN ROLE_ID ROLE_ID CHAR(36) NOT NULL COMMENT '角色ID';
           
      ALTER TABLE TPT_DOMAIN_MANAGER CHANGE COLUMN PERMISSION_ID PERMISSION_ID CHAR(36) NOT NULL COMMENT '权限ID';
           
      
alter TABLE TPT_MENU COMMENT = '菜单表' ENGINE=InnoDB DEFAULT CHARSET=utf8;
 
    ALTER TABLE TPT_MENU CHANGE COLUMN MENU_ID MENU_ID CHAR(36) NOT NULL COMMENT '菜单ID';
           
      ALTER TABLE TPT_MENU CHANGE COLUMN PARENT_MENU_ID PARENT_MENU_ID CHAR(36)  COMMENT '父菜单ID';
           
      ALTER TABLE TPT_MENU CHANGE COLUMN MENU_NAME MENU_NAME VARCHAR(10)  COMMENT '菜单名称';
           
      ALTER TABLE TPT_MENU CHANGE COLUMN TERMINAL_CATEGORY TERMINAL_CATEGORY CHAR(10)  COMMENT '终端类别';
           
      ALTER TABLE TPT_MENU CHANGE COLUMN DOMAIN_MANAGE_ID DOMAIN_MANAGE_ID VARCHAR(20) NOT NULL COMMENT '域管理ID';
           
      ALTER TABLE TPT_MENU CHANGE COLUMN ROUTING_ID ROUTING_ID CHAR(36) NOT NULL COMMENT '路由ID';
           
      
alter TABLE TPT_NAVIGATION COMMENT = '导航表' ENGINE=InnoDB DEFAULT CHARSET=utf8;
 
    ALTER TABLE TPT_NAVIGATION CHANGE COLUMN NAVIGATION_ID NAVIGATION_ID CHAR(36) NOT NULL COMMENT '导航ID';
           
      ALTER TABLE TPT_NAVIGATION CHANGE COLUMN PARENT_ID PARENT_ID CHAR(36)  COMMENT '父ID';
           
      ALTER TABLE TPT_NAVIGATION CHANGE COLUMN NAVIGATION_NAME NAVIGATION_NAME VARCHAR(10)  COMMENT '导航名称';
           
      ALTER TABLE TPT_NAVIGATION CHANGE COLUMN PATH PATH VARCHAR(20)  COMMENT '路径';
           
      ALTER TABLE TPT_NAVIGATION CHANGE COLUMN DESCR DESCR VARCHAR(50)  COMMENT '描述';
           
      ALTER TABLE TPT_NAVIGATION CHANGE COLUMN MENU_ID MENU_ID CHAR(36) NOT NULL COMMENT '菜单ID';
           
      ALTER TABLE TPT_NAVIGATION CHANGE COLUMN ROUTING_ID ROUTING_ID CHAR(36) NOT NULL COMMENT '路由ID';
           
      
alter TABLE TPT_PERMISSION COMMENT = '权限表' ENGINE=InnoDB DEFAULT CHARSET=utf8;
 
    ALTER TABLE TPT_PERMISSION CHANGE COLUMN PERMISSION_ID PERMISSION_ID CHAR(36) NOT NULL COMMENT '权限ID';
           
      ALTER TABLE TPT_PERMISSION CHANGE COLUMN PERMISSION_NAME PERMISSION_NAME CHAR(10) NOT NULL COMMENT '权限名称';
           
      ALTER TABLE TPT_PERMISSION CHANGE COLUMN DESCR DESCR VARCHAR(100)  COMMENT '描述';
           
      
alter TABLE TPT_PERMISSION_MATRIX COMMENT = '权限矩阵表' ENGINE=InnoDB DEFAULT CHARSET=utf8;
 
    ALTER TABLE TPT_PERMISSION_MATRIX CHANGE COLUMN ROLE_ID ROLE_ID CHAR(36) NOT NULL COMMENT '角色ID';
           
      ALTER TABLE TPT_PERMISSION_MATRIX CHANGE COLUMN PERMISSION_ID PERMISSION_ID CHAR(36) NOT NULL COMMENT '权限ID';
           
      
alter TABLE TPT_RESOURCE COMMENT = '资源组表' ENGINE=InnoDB DEFAULT CHARSET=utf8;
 
    ALTER TABLE TPT_RESOURCE CHANGE COLUMN RESOURCES_GROUP_ID RESOURCES_GROUP_ID CHAR(36) NOT NULL COMMENT '资源组ID';
           
      ALTER TABLE TPT_RESOURCE CHANGE COLUMN PARENT_RESOURCES_GROUP_ID PARENT_RESOURCES_GROUP_ID CHAR(36)  COMMENT '父资源组ID';
           
      ALTER TABLE TPT_RESOURCE CHANGE COLUMN GROUP_NAME GROUP_NAME VARCHAR(20) NOT NULL COMMENT '组名称';
           
      ALTER TABLE TPT_RESOURCE CHANGE COLUMN DESCR DESCR VARCHAR(50)  COMMENT '描述';
           
      ALTER TABLE TPT_RESOURCE CHANGE COLUMN ROLE_ID ROLE_ID CHAR(36) NOT NULL COMMENT '角色ID';
           
      ALTER TABLE TPT_RESOURCE CHANGE COLUMN PERMISSION_ID PERMISSION_ID CHAR(36) NOT NULL COMMENT '权限ID';
           
      ALTER TABLE TPT_RESOURCE CHANGE COLUMN LEVEL LEVEL INTEGER  COMMENT '级别';
           
      
alter TABLE TPT_ROLE COMMENT = '角色表' ENGINE=InnoDB DEFAULT CHARSET=utf8;
 
    ALTER TABLE TPT_ROLE CHANGE COLUMN ROLE_ID ROLE_ID CHAR(36) NOT NULL COMMENT '角色ID';
           
      ALTER TABLE TPT_ROLE CHANGE COLUMN ROLE_NAME ROLE_NAME CHAR(10) NOT NULL COMMENT '角色名称';
           
      ALTER TABLE TPT_ROLE CHANGE COLUMN DESCR DESCR VARCHAR(50)  COMMENT '描述';
           
      
alter TABLE TPT_ROUTER COMMENT = '路由表' ENGINE=InnoDB DEFAULT CHARSET=utf8;
 
    ALTER TABLE TPT_ROUTER CHANGE COLUMN ROUTING_ID ROUTING_ID CHAR(36) NOT NULL COMMENT '路由ID';
           
      ALTER TABLE TPT_ROUTER CHANGE COLUMN URL URL VARCHAR(256)  COMMENT 'URL';
           
      ALTER TABLE TPT_ROUTER CHANGE COLUMN PARAM PARAM VARCHAR(2000)  COMMENT '参数';
           
      ALTER TABLE TPT_ROUTER CHANGE COLUMN REMARKS REMARKS VARCHAR(20)  COMMENT '备注';
           
      ALTER TABLE TPT_ROUTER CHANGE COLUMN DOMAIN_MANAGE_ID DOMAIN_MANAGE_ID VARCHAR(20) NOT NULL COMMENT '域管理ID';
           
      ALTER TABLE TPT_ROUTER CHANGE COLUMN ROLE_ID ROLE_ID CHAR(36) NOT NULL COMMENT '角色ID';
           
      ALTER TABLE TPT_ROUTER CHANGE COLUMN PERMISSION_ID PERMISSION_ID CHAR(36) NOT NULL COMMENT '权限ID';
           
      
alter TABLE TPT_STYLE COMMENT = '样式表' ENGINE=InnoDB DEFAULT CHARSET=utf8;
 
    ALTER TABLE TPT_STYLE CHANGE COLUMN SYTLE_ID SYTLE_ID VARCHAR(20)  COMMENT '样式ID';
           
      ALTER TABLE TPT_STYLE CHANGE COLUMN SYTLE_NAME SYTLE_NAME VARCHAR(20)  COMMENT '样式名称';
           
      ALTER TABLE TPT_STYLE CHANGE COLUMN SYTLE_DESCR SYTLE_DESCR VARCHAR(20)  COMMENT '样式描述';
           
      ALTER TABLE TPT_STYLE CHANGE COLUMN USER_ID USER_ID CHAR(36)  COMMENT '用户ID';
           
      
alter TABLE TPT_USER COMMENT = '用户表' ENGINE=InnoDB DEFAULT CHARSET=utf8;
 
    ALTER TABLE TPT_USER CHANGE COLUMN USER_ID USER_ID CHAR(36) NOT NULL COMMENT '用户ID';
           
      ALTER TABLE TPT_USER CHANGE COLUMN USER_CATEGORY USER_CATEGORY CHAR(10)  COMMENT '用户类别';
           
      ALTER TABLE TPT_USER CHANGE COLUMN ROLE_ID ROLE_ID CHAR(36) NOT NULL COMMENT '角色ID';
           
      ALTER TABLE TPT_USER CHANGE COLUMN PERMISSION_ID PERMISSION_ID CHAR(36) NOT NULL COMMENT '权限ID';
           
      ALTER TABLE TPT_USER CHANGE COLUMN RESOURCES_GROUP_ID RESOURCES_GROUP_ID CHAR(36) NOT NULL COMMENT '资源组ID';
           
      
alter TABLE TPT_WEIXIN COMMENT = '微信用户表' ENGINE=InnoDB DEFAULT CHARSET=utf8;
 
    ALTER TABLE TPT_WEIXIN CHANGE COLUMN WEIXIN_NO WEIXIN_NO VARCHAR(18) NOT NULL COMMENT '微信号';
           
      ALTER TABLE TPT_WEIXIN CHANGE COLUMN RESOURCES_GROUP_ID RESOURCES_GROUP_ID CHAR(36) NOT NULL COMMENT '资源组ID';
           
      ALTER TABLE TPT_WEIXIN CHANGE COLUMN WEIXIN_USER_ID WEIXIN_USER_ID CHAR(36) NOT NULL COMMENT '微信用户ID';
           
      ALTER TABLE TPT_WEIXIN CHANGE COLUMN CREATE_TIME CREATE_TIME VARCHAR(20) NOT NULL COMMENT '创建时间';