server:
  port: ${APP_PORT:28503}
  compression:
    enabled: true
  tomcat:
    uri-encoding: UTF-8
spring:
  application: 
    name: paas_portal
  mvc:
    favicon:
      enabled: false
   #view:
      #prefix: /language
      #suffix: index.html
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${MYSQL_IP:121.41.14.148}:${MYSQL_PORT:3306}/paas_portal?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PWD:1qaz@WSX}
    # connectionURL="jdbc:mysql://121.41.14.148:3306/paas_language" userId="root" password="1qaz@WSX" />
mybatis:
  type-aliases-package: com.flat.paas.portal.domain
  mapper-locations: classpath*:persistence_mapper/*Mapper.xml
  config-location: classpath:mybatis-config.xml
#logging:
 # file: logs/language.log
  #level: debug