
CREATE TABLE TPT_CONTROL
(
	APPLICATION_ID  CHAR(36) NOT NULL,
	DESCR  VARCHAR(150) NULL,
	CREATOR  VARCHAR(20) NULL,
	CREATE_TIME  DATETIME NULL,
	LAST_UPDATE_PERSON  VARCHAR(20) NULL,
	LAST_UPDATE_TIME  DATETIME NULL,
	ROLE_ID  CHAR(36) NULL,
	PERMISSION_ID  CHAR(36) NULL,
	PATH_ID  CHAR(36) NULL,
	 PRIMARY KEY (APPLICATION_ID)
)
;



CREATE UNIQUE INDEX ipt_control ON TPT_CONTROL
(
	APPLICATION_ID
)
;



CREATE TABLE TPT_DICTIONARIES
(
	CLASS_CODE  CHAR(6) NULL,
	DESCR  VARCHAR(50) NULL,
	VALUE_CODE  CHAR(4) NULL,
	NAME  VARCHAR(50) NULL,
	CREATOR  CHAR(36) NOT NULL,
	CREATE_TIME  DATETIME NULL,
	LAST_UPDATE_PERSON  VARCHAR(20) NULL,
	LAST_UPDATE_TIME  DATETIME NULL,
	 PRIMARY KEY (CLASS_CODE,VALUE_CODE)
)
;



CREATE UNIQUE INDEX ipt_dictionaries ON TPT_DICTIONARIES
(
	CLASS_CODE,
	VALUE_CODE
)
;



CREATE TABLE TPT_INTERNATIONAL
(
	INTERNATIONAL_ID  CHAR(36) NOT NULL,
	INTERNATIONALKEY  VARCHAR(50) NULL,
	CHIANESE_NAME  VARCHAR(50) NULL,
	ENGLISH_NAME  VARCHAR(50) NULL,
	DESCR  VARCHAR(50) NULL,
	CREATOR  CHAR(36) NOT NULL,
	CREATE_TIME  DATETIME NULL,
	LAST_UPDATE_PERSON  VARCHAR(20) NULL,
	LAST_UPDATE_TIME  DATETIME NULL,
	 PRIMARY KEY (INTERNATIONAL_ID)
)
;



CREATE UNIQUE INDEX ipt_international ON TPT_INTERNATIONAL
(
	INTERNATIONAL_ID
)
;



CREATE UNIQUE INDEX xak1ipt_international ON TPT_INTERNATIONAL
(
	INTERNATIONALKEY
)
;



CREATE TABLE TPT_MENU
(
	MENU_ID  CHAR(36) NOT NULL,
	PARENT_MENU_ID  CHAR(36) NULL,
	MENU_NAME  VARCHAR(10) NULL,
	TERMINAL_CATEGORY  CHAR(10) NULL,
	LAST_UPDATE_PERSON  CHAR(36) NOT NULL,
	LAST_UPDATE_TIME  DATETIME NULL,
	CREATOR  CHAR(36) NOT NULL,
	CREATE_TIME  DATETIME NULL,
	 PRIMARY KEY (MENU_ID)
)
;



CREATE UNIQUE INDEX ipt_menu ON TPT_MENU
(
	MENU_ID
)
;



CREATE TABLE TPT_NAVIGATION
(
	NAVIGATION_ID  CHAR(36) NOT NULL,
	PARENT_ID  CHAR(36) NULL,
	NAVIGATION_NAME  VARCHAR(10) NULL,
	PATH  VARCHAR(20) NULL,
	DESCR  VARCHAR(50) NULL,
	MENU_ID  CHAR(36) NULL,
	CREATOR  CHAR(36) NOT NULL,
	CREATE_TIME  DATETIME NULL,
	LAST_UPDATE_PERSON  CHAR(36) NOT NULL,
	LAST_UPDATE_TIME  DATETIME NULL,
	 PRIMARY KEY (NAVIGATION_ID)
)
;



CREATE UNIQUE INDEX ipt_navigation ON TPT_NAVIGATION
(
	NAVIGATION_ID
)
;



CREATE TABLE TPT_PERMISSION
(
	PERMISSION_ID  CHAR(36) NOT NULL,
	PERMISSION_NAME  CHAR(10) NULL,
	DESCR  VARCHAR(100) NULL,
	CREATOR  VARCHAR(20) NULL,
	CREATE_TIME  DATETIME NULL,
	LAST_UPDATE_PERSON  VARCHAR(20) NULL,
	LAST_UPDATE_TIME  DATETIME NULL,
	 PRIMARY KEY (PERMISSION_ID)
)
;



CREATE UNIQUE INDEX ipt_permission ON TPT_PERMISSION
(
	PERMISSION_ID
)
;



CREATE TABLE TPT_PERMISSION_MATRIX
(
	ROLE_ID  CHAR(36) NOT NULL,
	PERMISSION_ID  CHAR(36) NOT NULL,
	 PRIMARY KEY (ROLE_ID,PERMISSION_ID)
)
;



CREATE UNIQUE INDEX ipt_permission_matrix ON TPT_PERMISSION_MATRIX
(
	ROLE_ID,
	PERMISSION_ID
)
;



CREATE TABLE TPT_RESOURCE_GROUP
(
	GROUP_ID  CHAR(36) NOT NULL,
	PARENT_GROUP_ID  CHAR(36) NULL,
	GROUP_NAME  VARCHAR(20) NULL,
	DESCR  VARCHAR(50) NULL,
	ROLE_ID  CHAR(36) NULL,
	PERMISSION_ID  CHAR(36) NULL,
	LEVEL  DATETIME NULL,
	CREATOR  CHAR(36) NOT NULL,
	CREATE_TIME  DATETIME NULL,
	LAST_UPDATE_PERSON  CHAR(36) NOT NULL,
	LAST_UPDATE_TIME  DATETIME NULL,
	 PRIMARY KEY (GROUP_ID)
)
;



CREATE UNIQUE INDEX ipt_resource_group ON TPT_RESOURCE_GROUP
(
	GROUP_ID
)
;



CREATE TABLE TPT_ROLE
(
	ROLE_ID  CHAR(36) NOT NULL,
	ROLE_NAME  CHAR(10) NOT NULL,
	DESCR  VARCHAR(50) NULL,
	CREATOR  VARCHAR(20) NULL,
	CREATE_TIME  DATETIME NULL,
	LAST_UPDATE_PERSON  CHAR(36) NOT NULL,
	LAST_UPDATE_TIME  DATETIME NULL,
	 PRIMARY KEY (ROLE_ID)
)
;



CREATE UNIQUE INDEX ipt_role ON TPT_ROLE
(
	ROLE_ID
)
;



CREATE TABLE TPT_USER
(
	USER_ID  CHAR(36) NOT NULL,
	USER_CATEGORY  CHAR(10) NULL,
	ROLE_ID  CHAR(36) NULL,
	PERMISSION_ID  CHAR(36) NULL,
	GROUP_ID  CHAR(36) NULL,
	CREATOR  CHAR(36) NOT NULL,
	CREATE_TIME  DATETIME NULL,
	LAST_UPDATE_PERSON  CHAR(36) NOT NULL,
	LAST_UPDATE_TIME  DATETIME NULL,
	 PRIMARY KEY (USER_ID)
)
;



CREATE UNIQUE INDEX ipt_user ON TPT_USER
(
	USER_ID
)
;



CREATE TABLE TPT_WEIXIN
(
	WEIXIN_NO  VARCHAR(18) NOT NULL,
	GROUP_ID  CHAR(36) NULL,
	WEIXIN_USER_ID  CHAR(36) NOT NULL,
	CREATE_TIME  VARCHAR(20) NULL,
	 PRIMARY KEY (WEIXIN_USER_ID)
)
;



CREATE UNIQUE INDEX ipt_weixin ON TPT_WEIXIN
(
	WEIXIN_USER_ID
)
;



alter TABLE TPT_CONTROL COMMENT = '访问控制列表' ENGINE=InnoDB DEFAULT CHARSET=utf8;
 
    ALTER TABLE TPT_CONTROL CHANGE COLUMN APPLICATION_ID APPLICATION_ID CHAR(36) NOT NULL COMMENT '应用ID';
           
      ALTER TABLE TPT_CONTROL CHANGE COLUMN DESCR DESCR VARCHAR(150)  COMMENT '描述';
           
      ALTER TABLE TPT_CONTROL CHANGE COLUMN CREATOR CREATOR VARCHAR(20)  COMMENT '创建人';
           
      ALTER TABLE TPT_CONTROL CHANGE COLUMN CREATE_TIME CREATE_TIME DATETIME  COMMENT '创建时间';
           
      ALTER TABLE TPT_CONTROL CHANGE COLUMN LAST_UPDATE_PERSON LAST_UPDATE_PERSON VARCHAR(20)  COMMENT '最后更新人';
           
      ALTER TABLE TPT_CONTROL CHANGE COLUMN LAST_UPDATE_TIME LAST_UPDATE_TIME DATETIME  COMMENT '最后更新时间';
           
      ALTER TABLE TPT_CONTROL CHANGE COLUMN ROLE_ID ROLE_ID CHAR(36)  COMMENT '角色ID';
           
      ALTER TABLE TPT_CONTROL CHANGE COLUMN PERMISSION_ID PERMISSION_ID CHAR(36)  COMMENT '权限ID';
           
      ALTER TABLE TPT_CONTROL CHANGE COLUMN PATH_ID PATH_ID CHAR(36)  COMMENT '路径ID';
           
      
alter TABLE TPT_DICTIONARIES COMMENT = '数据字典表' ENGINE=InnoDB DEFAULT CHARSET=utf8;
 
    ALTER TABLE TPT_DICTIONARIES CHANGE COLUMN CLASS_CODE CLASS_CODE CHAR(6)  COMMENT '类编码';
           
      ALTER TABLE TPT_DICTIONARIES CHANGE COLUMN DESCR DESCR VARCHAR(50)  COMMENT '描述';
           
      ALTER TABLE TPT_DICTIONARIES CHANGE COLUMN VALUE_CODE VALUE_CODE CHAR(4)  COMMENT '值编码';
           
      ALTER TABLE TPT_DICTIONARIES CHANGE COLUMN NAME NAME VARCHAR(50)  COMMENT '名称';
           
      ALTER TABLE TPT_DICTIONARIES CHANGE COLUMN CREATOR CREATOR CHAR(36) NOT NULL COMMENT '创建人';
           
      ALTER TABLE TPT_DICTIONARIES CHANGE COLUMN CREATE_TIME CREATE_TIME DATETIME  COMMENT '创建时间';
           
      ALTER TABLE TPT_DICTIONARIES CHANGE COLUMN LAST_UPDATE_PERSON LAST_UPDATE_PERSON VARCHAR(20)  COMMENT '最后更新人';
           
      ALTER TABLE TPT_DICTIONARIES CHANGE COLUMN LAST_UPDATE_TIME LAST_UPDATE_TIME DATETIME  COMMENT '最后更新时间';
           
      
alter TABLE TPT_INTERNATIONAL COMMENT = '国际化表' ENGINE=InnoDB DEFAULT CHARSET=utf8;
 
    ALTER TABLE TPT_INTERNATIONAL CHANGE COLUMN INTERNATIONAL_ID INTERNATIONAL_ID CHAR(36) NOT NULL COMMENT '国际化ID';
           
      ALTER TABLE TPT_INTERNATIONAL CHANGE COLUMN INTERNATIONALKEY INTERNATIONALKEY VARCHAR(50)  COMMENT '国际化Key';
           
      ALTER TABLE TPT_INTERNATIONAL CHANGE COLUMN CHIANESE_NAME CHIANESE_NAME VARCHAR(50)  COMMENT '中文名';
           
      ALTER TABLE TPT_INTERNATIONAL CHANGE COLUMN ENGLISH_NAME ENGLISH_NAME VARCHAR(50)  COMMENT '英文名';
           
      ALTER TABLE TPT_INTERNATIONAL CHANGE COLUMN DESCR DESCR VARCHAR(50)  COMMENT '描述';
           
      ALTER TABLE TPT_INTERNATIONAL CHANGE COLUMN CREATOR CREATOR CHAR(36) NOT NULL COMMENT '创建人';
           
      ALTER TABLE TPT_INTERNATIONAL CHANGE COLUMN CREATE_TIME CREATE_TIME DATETIME  COMMENT '创建时间';
           
      ALTER TABLE TPT_INTERNATIONAL CHANGE COLUMN LAST_UPDATE_PERSON LAST_UPDATE_PERSON VARCHAR(20)  COMMENT '最后更新人';
           
      ALTER TABLE TPT_INTERNATIONAL CHANGE COLUMN LAST_UPDATE_TIME LAST_UPDATE_TIME DATETIME  COMMENT '最后更新时间';
           
      
alter TABLE TPT_MENU COMMENT = '菜单列表' ENGINE=InnoDB DEFAULT CHARSET=utf8;
 
    ALTER TABLE TPT_MENU CHANGE COLUMN MENU_ID MENU_ID CHAR(36) NOT NULL COMMENT '菜单ID';
           
      ALTER TABLE TPT_MENU CHANGE COLUMN PARENT_MENU_ID PARENT_MENU_ID CHAR(36)  COMMENT '父菜单ID';
           
      ALTER TABLE TPT_MENU CHANGE COLUMN MENU_NAME MENU_NAME VARCHAR(10)  COMMENT '菜单名称';
           
      ALTER TABLE TPT_MENU CHANGE COLUMN TERMINAL_CATEGORY TERMINAL_CATEGORY CHAR(10)  COMMENT '终端类别';
           
      ALTER TABLE TPT_MENU CHANGE COLUMN LAST_UPDATE_PERSON LAST_UPDATE_PERSON CHAR(36) NOT NULL COMMENT '最后更新人';
           
      ALTER TABLE TPT_MENU CHANGE COLUMN LAST_UPDATE_TIME LAST_UPDATE_TIME DATETIME  COMMENT '最后更新时间';
           
      ALTER TABLE TPT_MENU CHANGE COLUMN CREATOR CREATOR CHAR(36) NOT NULL COMMENT '创建人';
           
      ALTER TABLE TPT_MENU CHANGE COLUMN CREATE_TIME CREATE_TIME DATETIME  COMMENT '创建时间';
           
      
alter TABLE TPT_NAVIGATION COMMENT = '导航列表' ENGINE=InnoDB DEFAULT CHARSET=utf8;
 
    ALTER TABLE TPT_NAVIGATION CHANGE COLUMN NAVIGATION_ID NAVIGATION_ID CHAR(36) NOT NULL COMMENT '导航ID';
           
      ALTER TABLE TPT_NAVIGATION CHANGE COLUMN PARENT_ID PARENT_ID CHAR(36)  COMMENT '父ID';
           
      ALTER TABLE TPT_NAVIGATION CHANGE COLUMN NAVIGATION_NAME NAVIGATION_NAME VARCHAR(10)  COMMENT '导航名称';
           
      ALTER TABLE TPT_NAVIGATION CHANGE COLUMN PATH PATH VARCHAR(20)  COMMENT '路径';
           
      ALTER TABLE TPT_NAVIGATION CHANGE COLUMN DESCR DESCR VARCHAR(50)  COMMENT '描述';
           
      ALTER TABLE TPT_NAVIGATION CHANGE COLUMN MENU_ID MENU_ID CHAR(36)  COMMENT '菜单ID';
           
      ALTER TABLE TPT_NAVIGATION CHANGE COLUMN CREATOR CREATOR CHAR(36) NOT NULL COMMENT '创建人';
           
      ALTER TABLE TPT_NAVIGATION CHANGE COLUMN CREATE_TIME CREATE_TIME DATETIME  COMMENT '创建时间';
           
      ALTER TABLE TPT_NAVIGATION CHANGE COLUMN LAST_UPDATE_PERSON LAST_UPDATE_PERSON CHAR(36) NOT NULL COMMENT '最后更新人';
           
      ALTER TABLE TPT_NAVIGATION CHANGE COLUMN LAST_UPDATE_TIME LAST_UPDATE_TIME DATETIME  COMMENT '最后更新时间';
           
      
alter TABLE TPT_PERMISSION COMMENT = '权限列表' ENGINE=InnoDB DEFAULT CHARSET=utf8;
 
    ALTER TABLE TPT_PERMISSION CHANGE COLUMN PERMISSION_ID PERMISSION_ID CHAR(36) NOT NULL COMMENT '权限ID';
           
      ALTER TABLE TPT_PERMISSION CHANGE COLUMN PERMISSION_NAME PERMISSION_NAME CHAR(10)  COMMENT '权限名称';
           
      ALTER TABLE TPT_PERMISSION CHANGE COLUMN DESCR DESCR VARCHAR(100)  COMMENT '描述';
           
      ALTER TABLE TPT_PERMISSION CHANGE COLUMN CREATOR CREATOR VARCHAR(20)  COMMENT '创建人';
           
      ALTER TABLE TPT_PERMISSION CHANGE COLUMN CREATE_TIME CREATE_TIME DATETIME  COMMENT '创建时间';
           
      ALTER TABLE TPT_PERMISSION CHANGE COLUMN LAST_UPDATE_PERSON LAST_UPDATE_PERSON VARCHAR(20)  COMMENT '最后更新人';
           
      ALTER TABLE TPT_PERMISSION CHANGE COLUMN LAST_UPDATE_TIME LAST_UPDATE_TIME DATETIME  COMMENT '最后更新时间';
           
      
alter TABLE TPT_PERMISSION_MATRIX COMMENT = '权限矩阵列表' ENGINE=InnoDB DEFAULT CHARSET=utf8;
 
    ALTER TABLE TPT_PERMISSION_MATRIX CHANGE COLUMN ROLE_ID ROLE_ID CHAR(36) NOT NULL COMMENT '角色ID';
           
      ALTER TABLE TPT_PERMISSION_MATRIX CHANGE COLUMN PERMISSION_ID PERMISSION_ID CHAR(36) NOT NULL COMMENT '权限ID';
           
      
alter TABLE TPT_RESOURCE_GROUP COMMENT = '资源组表' ENGINE=InnoDB DEFAULT CHARSET=utf8;
 
    ALTER TABLE TPT_RESOURCE_GROUP CHANGE COLUMN GROUP_ID GROUP_ID CHAR(36) NOT NULL COMMENT '组ID';
           
      ALTER TABLE TPT_RESOURCE_GROUP CHANGE COLUMN PARENT_GROUP_ID PARENT_GROUP_ID CHAR(36)  COMMENT '父组ID';
           
      ALTER TABLE TPT_RESOURCE_GROUP CHANGE COLUMN GROUP_NAME GROUP_NAME VARCHAR(20)  COMMENT '组名称';
           
      ALTER TABLE TPT_RESOURCE_GROUP CHANGE COLUMN DESCR DESCR VARCHAR(50)  COMMENT '描述';
           
      ALTER TABLE TPT_RESOURCE_GROUP CHANGE COLUMN ROLE_ID ROLE_ID CHAR(36)  COMMENT '角色ID';
           
      ALTER TABLE TPT_RESOURCE_GROUP CHANGE COLUMN PERMISSION_ID PERMISSION_ID CHAR(36)  COMMENT '权限ID';
           
      ALTER TABLE TPT_RESOURCE_GROUP CHANGE COLUMN LEVEL LEVEL DATETIME  COMMENT '级别';
           
      ALTER TABLE TPT_RESOURCE_GROUP CHANGE COLUMN CREATOR CREATOR CHAR(36) NOT NULL COMMENT '创建人';
           
      ALTER TABLE TPT_RESOURCE_GROUP CHANGE COLUMN CREATE_TIME CREATE_TIME DATETIME  COMMENT '创建时间';
           
      ALTER TABLE TPT_RESOURCE_GROUP CHANGE COLUMN LAST_UPDATE_PERSON LAST_UPDATE_PERSON CHAR(36) NOT NULL COMMENT '最后更新人';
           
      ALTER TABLE TPT_RESOURCE_GROUP CHANGE COLUMN LAST_UPDATE_TIME LAST_UPDATE_TIME DATETIME  COMMENT '最后更新时间';
           
      
alter TABLE TPT_ROLE COMMENT = '角色列表' ENGINE=InnoDB DEFAULT CHARSET=utf8;
 
    ALTER TABLE TPT_ROLE CHANGE COLUMN ROLE_ID ROLE_ID CHAR(36) NOT NULL COMMENT '角色ID';
           
      ALTER TABLE TPT_ROLE CHANGE COLUMN ROLE_NAME ROLE_NAME CHAR(10) NOT NULL COMMENT '角色名称';
           
      ALTER TABLE TPT_ROLE CHANGE COLUMN DESCR DESCR VARCHAR(50)  COMMENT '描述';
           
      ALTER TABLE TPT_ROLE CHANGE COLUMN CREATOR CREATOR VARCHAR(20)  COMMENT '创建人';
           
      ALTER TABLE TPT_ROLE CHANGE COLUMN CREATE_TIME CREATE_TIME DATETIME  COMMENT '创建时间';
           
      ALTER TABLE TPT_ROLE CHANGE COLUMN LAST_UPDATE_PERSON LAST_UPDATE_PERSON CHAR(36) NOT NULL COMMENT '最后更新人';
           
      ALTER TABLE TPT_ROLE CHANGE COLUMN LAST_UPDATE_TIME LAST_UPDATE_TIME DATETIME  COMMENT '最后更新时间';
           
      
alter TABLE TPT_USER COMMENT = '用户列表' ENGINE=InnoDB DEFAULT CHARSET=utf8;
 
    ALTER TABLE TPT_USER CHANGE COLUMN USER_ID USER_ID CHAR(36) NOT NULL COMMENT '用户ID';
           
      ALTER TABLE TPT_USER CHANGE COLUMN USER_CATEGORY USER_CATEGORY CHAR(10)  COMMENT '用户类别';
           
      ALTER TABLE TPT_USER CHANGE COLUMN ROLE_ID ROLE_ID CHAR(36)  COMMENT '角色ID';
           
      ALTER TABLE TPT_USER CHANGE COLUMN PERMISSION_ID PERMISSION_ID CHAR(36)  COMMENT '权限ID';
           
      ALTER TABLE TPT_USER CHANGE COLUMN GROUP_ID GROUP_ID CHAR(36)  COMMENT '组ID';
           
      ALTER TABLE TPT_USER CHANGE COLUMN CREATOR CREATOR CHAR(36) NOT NULL COMMENT '创建人';
           
      ALTER TABLE TPT_USER CHANGE COLUMN CREATE_TIME CREATE_TIME DATETIME  COMMENT '创建时间';
           
      ALTER TABLE TPT_USER CHANGE COLUMN LAST_UPDATE_PERSON LAST_UPDATE_PERSON CHAR(36) NOT NULL COMMENT '最后更新人';
           
      ALTER TABLE TPT_USER CHANGE COLUMN LAST_UPDATE_TIME LAST_UPDATE_TIME DATETIME  COMMENT '最后更新时间';
           
      
alter TABLE TPT_WEIXIN COMMENT = '微信用户表' ENGINE=InnoDB DEFAULT CHARSET=utf8;
 
    ALTER TABLE TPT_WEIXIN CHANGE COLUMN WEIXIN_NO WEIXIN_NO VARCHAR(18) NOT NULL COMMENT '微信号';
           
      ALTER TABLE TPT_WEIXIN CHANGE COLUMN GROUP_ID GROUP_ID CHAR(36)  COMMENT '组ID';
           
      ALTER TABLE TPT_WEIXIN CHANGE COLUMN WEIXIN_USER_ID WEIXIN_USER_ID CHAR(36) NOT NULL COMMENT '微信用户ID';
           
      ALTER TABLE TPT_WEIXIN CHANGE COLUMN CREATE_TIME CREATE_TIME VARCHAR(20)  COMMENT '创建时间';